language: java
jdk:
- oraclejdk8

after_success:
  - ./gradlew shadowJar

deploy:
  provider: releases
  api_key:
    secure: AukcZW0aTeSAHYck49pNedhcFNpD9axtLPUsPGq2c0ZqU/YWqLfvsoSoxu2f9cLL4dZwm1v7F33JWhV/H/WDxl2aOvUv1Iw2F7zIBN+OvOr4JqpssHyX2cDl7JaqM/KRc/yeBxsKZIOUR4OjIZ0umsAlsKe48hUaR+XQYNxu2xcdGJg4iaKUpBbR6mnOayUyMypeaBJwPni2cDO2fD0p/poluLj3SfUG+iF8Kb7dW7t0OlGwZvbIjNGefNsJ27hhxGBEDplUIsU/oK8u2+DJM+YANROfP3RsjjrUL82AiKzfNdPzexXfaHfeHueMOudDzbO44jwwESiN85JYPxQKcSi9Vpwiis8RtRsIgbR7GcDXvj+GTa1gXpwJ6PN79ZqzU6D3nDeeOJcb6kRRXsQLuRwFp3TjeWw959v/Ako12ZZqwAmI0Ghqa69lPi+tvTGZPrUnH/+HfiyfPkQQbdTfHIUwA3kCJYctzsfXlyAyTRAhgBUG/4zvmTUA8Rh/L9G9wy8etpGjrB1Y/rsJ6I8hlzdJuieKB8e6q6jeEVaj4wh9tP35y6S88v4+Ft49aJW3ccueGsJ02K9djQCS9K3BeCI52HpwpTQIIGs62wxQVZdBGb59zK74XyJGM3yVk1WhBjZ4mYmgJaL0eNmcPYRoJU276SvPjwD/S4JZ156/4cc=
  file: build/DiscourseWhitelist-*.jar
  file_glob: true
  on:
    repo: the-obsidian/DiscourseWhitelist
    tags: true
