name: DiscourseWhitelist
version: '@VERSION@'
description: '@DESCRIPTION@'

author: Jacob Gillespie
website: '@URL@'

main: gg.obsidian.discoursewhitelist.Plugin

permissions:
  discoursewhitelist.reload:
    description: Reload the Discourse Whitelist configuration
    default: op

commands:
  discoursewhitelist:
    description: Reload the Discourse Whitelist config
    usage: /discoursewhitelist reload
